[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "pyqt6-sip>=13.10.0",
    "pyqt6>=6.8.1",
    "pyqt6-qt6>=6.8.2",
]
